      - name: OpenAI Release Notes Action
        uses: diegobugs/openai-release-notes-action@v1.1.6
        with:
          language: "en"  # ✅ Default is English
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}  # ✅ Ensure this secret is added to GitHub
          token: ${{ secrets.GITHUB_TOKEN }}  # ✅ GitHub token for accessing commit history
          version: "v1.0.0"  # ✅ Update with the correct release version
          model: "gpt-4o"  # ✅ Best OpenAI model available
          use-github-generated-notes: true  # ✅ Use GitHub's release notes if available
          use-mention-commits-prs: true  # ✅ Include mentions of commits and PRs in the summary
