      - name: OpenAI Release Notes Action
        uses: diegobugs/openai-release-notes-action@v1.1.6
        with:
          language: "en"  # ✅ Default output language: English
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}  # ✅ Ensure this secret is set in GitHub Actions
          token: ${{ secrets.GITHUB_TOKEN }}  # ✅ GitHub token for accessing commit history
          version: "v1.0.0"  # ✅ Set the release version dynamically if needed
          model: "gpt-4o"  # ✅ Uses OpenAI's GPT-4o model for summarization
          use-github-generated-notes: true  # ✅ Utilize GitHub's built-in release notes if available
          use-mention-commits-prs: true  # ✅ Include references to commits and PRs in the summary
