name: Summarize Latest PR with AI

on:
  workflow_dispatch:  # ✅ Manual trigger only

permissions:
  contents: write  # ✅ Required for creating releases

jobs:
  summarize-latest-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ✅ Ensure we have full history

      - name: Generate AI Summary from Commits
        uses: post-op/chatgpt-release@v1
        with:
          version: 'v1.0.0'  # ✅ You can update this dynamically later
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Release Notes
        run: |
          echo "✅ AI-generated release notes are ready."
