name: Test OpenAI API Summarization

on:
  workflow_dispatch:  # ✅ Allows manual trigger

permissions:
  contents: read

jobs:
  summarize-text:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Define Input Text
        run: |
          INPUT_TEXT="GitHub Actions automate workflows. They allow developers to automate software development tasks such as CI/CD, testing, and deployment."
          echo "INPUT_TEXT=$INPUT_TEXT" >> $GITHUB_ENV

      - name: Call OpenAI for Summarization
        run: |
          echo "Calling OpenAI API..."

          # Escape special characters in input text
          ESCAPED_TEXT=$(echo "$INPUT_TEXT" | jq -Rs .)

          # Send request to OpenAI
          RESPONSE=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -H "Content-Type: application/json" \
            --data "{
              \"model\": \"gpt-4o\",
              \"messages\": [
                {\"role\": \"system\", \"content\": \"You are a helpful assistant that summarizes text.\"},
                {\"role\": \"user\", \"content\": \"Summarize this: $ESCAPED_TEXT\"}
              ]
            }")

          # Extract summary from API response
          SUMMARY=$(echo "$RESPONSE" | jq -r '.choices[0].message.content')

          # Print summary
          echo "Summary: $SUMMARY"

        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
