name: Weekly Automated Release Notes

on:
  schedule:
    - cron: "0 20 * * 5"  # ✅ Runs every Friday at 3 PM EST (20:00 UTC)
  workflow_dispatch:  # ✅ Allows manual trigger

permissions:
  contents: write
  pull-requests: write  # ✅ Required to modify PR labels

jobs:
  generate-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ✅ Ensures full commit history for PR data

      - name: Get PRs from the Last 7 Days
        id: get-prs
        run: |
          PR_LIST_JSON=$(gh pr list --state merged --label release --json number,title,author,mergedAt,body --limit 100)
          
          # Validate if PRs exist
          if [[ -z "$PR_LIST_JSON" || "$PR_LIST_JSON" == "[]" ]]; then
            echo "No valid PRs found. Skipping AI summarization."
            echo "PR_LIST_JSON=[]" >> $GITHUB_ENV
            exit 0  # ✅ Exit gracefully
          fi

          # Save PR list as JSON file for debugging
          echo "$PR_LIST_JSON" > pr_data.json
          
          echo "PR_LIST_JSON<<EOF" >> $GITHUB_ENV
          echo "$PR_LIST_JSON" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Draft GitHub Release (Prepare JSON for OpenAI)
        id: draft-release
        run: |
          RELEASE_DRAFT=$(echo "$PR_LIST_JSON" | jq -r '
            map({
              title: .title,
              author: .author.name // .author.login,
              date: (.mergedAt | split("-") | .[1] + "/" + .[2][:2] + "/" + .[0]),
              body: .body
            })'
          )

          echo "RELEASE_DRAFT<<EOF" >> $GITHUB_ENV
          echo "$RELEASE_DRAFT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          # Save for debugging
          echo "$RELEASE_DRAFT" > release_draft.json

      - name: Generate Unique Release Tag
        id: release-tag
        run: |
          BASE_TAG=$(date +'%Y-%m-%d').v1
          TAG=$BASE_TAG
          COUNTER=1
          
          while gh release view "$TAG" >/dev/null 2>&1; do
            COUNTER=$((COUNTER + 1))
            TAG="${BASE_TAG}.${COUNTER}"
          done
          
          echo "RELEASE_TAG=$TAG" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Summarize Release Notes with OpenAI
        id: ai-summary
        run: |
          # Escape JSON safely
          ESCAPED_RELEASE=$(echo "$RELEASE_DRAFT" | jq -Rs .)

          # Construct JSON Payload for OpenAI
          JSON_PAYLOAD=$(jq -n --arg text "$ESCAPED_RELEASE" '{
            model: "gpt-4o",
            messages: [
              { role: "system", content: "You are an AI assistant that summarizes release notes for a GitHub project. Provide a clear, concise summary." },
              { role: "user", content: "Summarize the following PRs into a concise, user-friendly release note: \($text)" }
            ]
          }')

          echo "Generated JSON Payload:"
          echo "$JSON_PAYLOAD" | jq .

          # Send request to OpenAI
          RESPONSE=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            --data-raw "$JSON_PAYLOAD")

          echo "Raw OpenAI Response: $RESPONSE"

          # Extract summary from API response
          SUMMARY=$(echo "$RESPONSE" | jq -r '.choices[0].message.content // "AI failed to generate a summary."')

          echo "Generated AI Summary: $SUMMARY"

          # Store AI Summary for later use
          echo "AI_SUMMARY<<EOF" >> $GITHUB_ENV
          echo "$SUMMARY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Create GitHub Release with AI Summary
        run: |
          RELEASE_TITLE="Weekly Release Notes - $(date +'%B %d, %Y')"  # ✅ New title format: Month DD, YYYY
          
          gh release create "${{ env.RELEASE_TAG }}" \
            --title "$RELEASE_TITLE" \
            --notes "### AI-Generated Summary\n\n${{ env.AI_SUMMARY }}\n\n### PR Details\n${{ env.RELEASE_DRAFT }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update PR Labels (Change 'release' → 'released')
        run: |
          PR_NUMBERS=$(echo "$PR_LIST_JSON" | jq -r 'map(.number) | join(" ")')

          for PR in $PR_NUMBERS; do
            gh pr edit "$PR" --remove-label "release" --add-label "released"
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
