name: Weekly Automated Release Notes

on:
  schedule:
    - cron: "0 20 * * 5"  # ✅ Runs every Friday at 3 PM EST (20:00 UTC)
  workflow_dispatch:  # ✅ Allows manual trigger

permissions:
  contents: write
  pull-requests: write  # ✅ Required to modify PR labels

jobs:
  generate-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ✅ Ensures full commit history for PR data

      - name: Get PRs from the Last 7 Days
        id: get-prs
        run: |
          PR_LIST=$(gh pr list --state merged --label release --json number,title,author,mergedAt,body --limit 100 --jq '
          map(select(.mergedAt > "'$(date -u --date="7 days ago" +%Y-%m-%dT%H:%M:%SZ)'")) | 
          map(
            "- **\(.title)**\n" +  
            "- **Author:** \(.author.name // .author.login)\n" +  # ✅ Show full name; fallback to username
            "- **Date:** \(.mergedAt | split("-") | .[1] + "/" + .[2][:2] + "/" + .[0])\n\n" +  # ✅ Convert YYYY-MM-DD to MM/DD/YYYY
            "\(.body)\n"
          ) | join("\n\n")')

          PR_NUMBERS=$(gh pr list --state merged --label release --json number --jq 'map(.number) | join(" ")')

          echo "$PR_LIST" > changelog.md
          echo "PR_LIST<<EOF" >> $GITHUB_ENV
          echo "$PR_LIST" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "PR_NUMBERS=$PR_NUMBERS" >> $GITHUB_ENV  # Store PR numbers for later
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Unique Release Tag
        id: release-tag
        run: |
          BASE_TAG=$(date +'%Y-%m-%d').v1
          TAG=$BASE_TAG
          COUNTER=1
          
          while gh release view "$TAG" >/dev/null 2>&1; do
            COUNTER=$((COUNTER + 1))
            TAG="${BASE_TAG}.${COUNTER}"
          done
          
          echo "RELEASE_TAG=$TAG" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        run: |
          RELEASE_TITLE="Weekly Release Notes - $(date +'%B %d, %Y')"  # ✅ New title format: Month DD, YYYY

          gh release create "${{ env.RELEASE_TAG }}" --title "$RELEASE_TITLE" --notes "${{ env.PR_LIST }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update PR Labels (Change 'release' → 'released')
        run: |
          for PR in ${{ env.PR_NUMBERS }}; do
            gh pr edit "$PR" --remove-label "release" --add-label "released"
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
